config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :games
  resources :players
  resources :participants, only: %i[index create]
  root to: 'leaderboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  # validations
  validates :name, presence: true

  # relationships/associations
  has_many :participants
  belongs_to :winner, class_name: 'Player', foreign_key: :player_id

  accepts_nested_attributes_for :participants, reject_if: :all_blank

  after_commit :update_player, on: :create

  def participants_name
    participants.map { |participant| participant.player.name }
  end

  private

  def update_player
    loser_id = participants.pluck(:player_id).excluding(winner.id)
    loser = Player.where(id: loser_id).first
    loser.losses += 1
    loser.save

    high_score = winning_score > winner.highest_score ? winning_score : winner.highest_score
    winner.highest_score = high_score
    winner.wins += 1
    winner.average_score = (winner.total_winning_games.sum(:winning_score) / winner.wins)
    winner.save
  end
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  # relationships/associations
  belongs_to :game
  belongs_to :player
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  # validations
  validates :first_name, :last_name, :phone_number, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_many :games

  def name
    "#{first_name} #{last_name}"
  end

  def total_winning_games
    games.where(winner: self)
  end

  def highest_score_details
    game = games.where(winner: self, winning_score: highest_score).first
    opponent = game&.participants&.where&.not(player_id: id)&.first&.player
    { highest_score: highest_score, game_name: game&.name, opponent: opponent&.name }
  end

  def ten_games_played?
    total_games_played >= 10
  end

  def total_games_played
    [wins, losses].sum
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  def index
    @games = Game.all
  end

  def show; end

  def new
    @game = Game.new
    2.times do
      @game.participants.build
    end
  end

  def edit; end

  def create
    @game = Game.new(game_params)
    set_other_attributes(@game)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game completed' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :description, participants_attributes: %i[player_id])
  end

  def set_other_attributes(game)
    game.winning_score = rand(80..100)
    game.losing_score = rand(60..79)
    game.player_id = game.participants.map(&:player_id).sample
  end
end

app/controllers/leaderboards_controller.rb
# frozen_string_literal: true

class LeaderboardsController < ApplicationController
  def index
    @collection = Player.select(&:ten_games_played?)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  def index
    @players = Player.all
  end

  def show; end

  def new
    @player = Player.new
  end

  def edit; end

  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_path, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_player
    @player = Player.find_by(id: params[:id])
  end

  def player_params
    params.require(:player).permit(:first_name, :last_name, :email, :phone_number)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_class(link_path)
    controller_name == link_path ? 'active' : ''
  end

  def page_title
    controller_name == 'leaderboards' ? t('leaderboard.title') : controller_name.titleize
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/leaderboards_helper.rb
# frozen_string_literal: true

module LeaderboardsHelper
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-6">
    <%= form.label :name %><span class='text-danger'>*</span>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <%= form.fields_for :participants, @game.participants.first do |member_form| %>
    <div class='col-md-6'>
      <strong><label class='form-label'>Member</label></strong>
      <span class='text-danger'>*</span>
      <%= member_form.collection_select :player_id, Player.all, :id, :name, {prompt: 'Select Member'}, {id: 'game_member_id', class: 'form-select form-select-lg mb-3', required: true} %>
    </div>
  <% end %>

  <%= form.fields_for :participants, @game.participants.last do |opponent_form| %>
    <div class='col-md-6'>
      <strong><label class='form-label'>Oppenent</label></strong>
      <span class='text-danger'>*</span>
      <%= opponent_form.collection_select :player_id, Player.all, :id, :name, {prompt: 'Select Opponent'}, {id: 'game_opponent_id', class: 'form-select form-select-lg mb-3', required: true} %>
    </div>
  <% end %>

  <div class='row mt-3'>
    <div class="form-group col-md-6">
      <%= form.submit t('submit'), class: 'btn btn-primary' %>
      <%= link_to t('back'), games_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  var member_list = '#game_member_id'
  var opponent_list = '#game_opponent_id'
  var selector_ids = $(`${member_list}, ${opponent_list}`)
  selector_ids.on('change', function () {
    var member_field_change = $(this).attr('id') == 'game_member_id'
    var update_field = member_field_change ? opponent_list : member_list
    var selected_value = $(this).val();
    if (selected_value != ''){
      $(`${update_field} option[value='`+ selected_value +"']").hide();
      $(`${update_field} option[value!='`+ selected_value +"']").show();
    } else if (selected_value == '' && $(update_field).val() == '') {
      selector_ids.children().show();
    }
  })
</script>

app/views/games/edit.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= t('game.edit') %></h3>
</div>
<%= render 'form', game: @game %>

app/views/games/index.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= page_title %></h3>
  <%= link_to new_game_path, class: 'btn btn-primary' do %>
    <%= t('game.add') %>
  <% end %>
</div>
<p id="notice"><%= notice %></p>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Players</th>
        <th scope="col">Winner</th>
        <th scope="col">Winning Score</th>
        <th scope="col">Losing score</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each.with_index(1) do |game, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= game.name %></td>
          <td><%= game.participants_name.join(" <=> ") %></td>
          <td><%= game.winner.name %></td>
          <td><%= game.winning_score %></td>
          <td><%= game.losing_score %></td>
          <td><%= link_to 'Show', game %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/new.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= t('game.add') %></h3>
</div>

<%= render 'form', game: @game %>

app/views/games/show.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= t('game.show') %></h3>
</div>
<p id="notice"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @game.name %></h5>
    <p class="card-text"><%= @game.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      Participants:
      <hr/>
      <% @game.participants_name.each do |player_name| %>
        <span><%= player_name %></span><br/>
      <% end %>
    </li>
    <li class="list-group-item">
      Winner: <%= @game.winner.name %>
    </li>
    <li class="list-group-item">
      Winning Score: <%= @game.winning_score %>
    </li>
    <li class="list-group-item">
      Losing Score: <%= @game.losing_score %>
    </li>
  </ul>
</div>

<div class='row mt-3'>
  <div class="form-group col-md-6">
    <%= link_to t('back'), games_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">ScrabbleClub</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to root_path, class: "nav-link #{active_class('leaderboards')}" do %>
                  <span data-feather="home"></span>
                  <%= t('leaderboard.title') %>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to players_path, class: "nav-link #{active_class('players')}" do %>
                  <span data-feather="home"></span>
                  <%= t('player.title') %>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to games_path, class: "nav-link #{active_class('games')}" do %>
                  <span data-feather="home"></span>
                   <%= t('participant.play_game') %>
                <% end %>
              </li>
            </ul>

          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/leaderboards/index.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= page_title %></h3>
</div>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= t('leaderboard.player') %></th>
        <th scope="col"><%= t('leaderboard.total_game') %></th>
        <th scope="col"><%= t('leaderboard.average_score') %></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each.with_index(1) do |player, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= player.name %></td>
          <td><%= player.total_games_played %></td>
          <td><%= player.average_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-6">
    <%= form.label :first_name %><span class='text-danger'>*</span>
    <%= form.text_field :first_name, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :last_name %><span class='text-danger'>*</span>
    <%= form.text_field :last_name, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :email %><span class='text-danger'>*</span>
    <%= form.text_field :email, class: 'form-control', required: true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :phone_number %><span class='text-danger'>*</span>
    <%= form.text_field :phone_number, class: 'form-control', required: true %>
  </div>

  <div class='row mt-3'>
    <div class="form-group col-md-6">
      <%= form.submit t('submit'), class: 'btn btn-primary' %>
      <%= link_to t('back'), players_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= t('player.edit') %></h3>
</div>
<%= render 'form', player: @player %>

app/views/players/index.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= page_title %></h3>
  <%= link_to new_player_path, class: 'btn btn-primary' do %>
    <%= t('player.add') %>
  <% end %>
</div>
<p id="notice"><%= notice %></p>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone number</th>
        <th scope="col" colspan="2" class='text-center'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @players.each.with_index(1) do |player, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= player.first_name %></td>
          <td><%= player.last_name %></td>
          <td><%= player.email %></td>
          <td><%= player.phone_number %></td>
          <td><%= link_to 'Show', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/players/new.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= t('player.add') %></h3>
</div>

<%= render 'form', player: @player %>

app/views/players/show.html.erb
<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h3><%= t('player.show') %></h3>
</div>
<p id="notice"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @player.name %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Email: <%= @player.email %></li>
    <li class="list-group-item">Phone Number: <%= @player.phone_number %></li>
    <li class="list-group-item">Total Games Wins: <%= @player.wins %></li>
    <li class="list-group-item">Total Games losses: <%= @player.losses %></li>
    <li class="list-group-item">Average Score: <%= @player.average_score %></li>
    <li class="list-group-item">
      Highest Score Details:
      <hr/>
      <% highest_score_details = @player.highest_score_details %>
      Highest score: <%= highest_score_details[:highest_score] %>
      <br/>
      Game: <%= highest_score_details[:game_name] %>
      <br/>
      Opponent: <%= highest_score_details[:opponent] %>
    </li>
  </ul>
</div>

<div class='row mt-3'>
  <div class="form-group col-md-6">
    <%= link_to 'Edit', edit_player_path(@player), class: 'btn btn-primary' %>
    <%= link_to t('back'), players_path, class: 'btn btn-secondary' %>
  </div>
</div>